language: go

go:
  - 1.12

install:
    - go get github.com/Urethramancer/cross
    - go get github.com/Urethramancer/pos
    - go get github.com/Urethramancer/signor
    - go get github.com/lib/pq
    - go get github.com/peterh/liner

include:
  - os: linux
    go: 1.12.x
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod

